-- Esquema PostgreSQL para Artify SENA PostgreSQL.
-- Mantiene nombres de tablas y columnas del modelo anterior para reducir cambios en el backend.

DROP VIEW IF EXISTS "v_usuarios_activos";
DROP TABLE IF EXISTS "OPERACION";
DROP TABLE IF EXISTS "SESION_EDICION";
DROP TABLE IF EXISTS "IMAGEN";
DROP TABLE IF EXISTS "CONFIGURACION";
DROP TABLE IF EXISTS "USUARIO";

CREATE TABLE "USUARIO" (
  "usr_id_usuario" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usr_nombres" varchar(100) NOT NULL,
  "usr_apellidos" varchar(100) NOT NULL,
  "usr_cedula" varchar(20) NOT NULL UNIQUE,
  "usr_fecha_nacimiento" date NOT NULL,
  "usr_correo" varchar(150) NOT NULL UNIQUE,
  "usr_contrasena" varchar(255) NOT NULL,
  "usr_fecha_registro" timestamp DEFAULT CURRENT_TIMESTAMP,
  "usr_ultimo_acceso" timestamp DEFAULT NULL,
  "usr_sesion_activa" boolean DEFAULT false,
  "usr_estado_usuario" varchar(20) DEFAULT 'activo'
    CHECK ("usr_estado_usuario" IN ('activo', 'inactivo', 'suspendido')),
  "usr_rol" varchar(20) NOT NULL DEFAULT 'usuario'
    CHECK ("usr_rol" IN ('usuario', 'admin'))
);

CREATE TABLE "CONFIGURACION" (
  "cfg_id_configuracion" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cfg_usr_id_usuario" integer NOT NULL UNIQUE,
  "cfg_tema" varchar(20) DEFAULT 'oscuro'
    CHECK ("cfg_tema" IN ('claro', 'oscuro', 'auto')),
  "cfg_idioma" varchar(10) DEFAULT 'es',
  "cfg_atajos_teclado" jsonb DEFAULT NULL,
  "cfg_mostrar_ayudas" boolean DEFAULT true,
  "cfg_calidad_exportacion" varchar(20) DEFAULT 'alta'
    CHECK ("cfg_calidad_exportacion" IN ('baja', 'media', 'alta', 'maxima')),
  "cfg_configuracion_avanzada" jsonb DEFAULT NULL,
  "cfg_fecha_actualizacion" timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "configuracion_usuario_fk"
    FOREIGN KEY ("cfg_usr_id_usuario")
    REFERENCES "USUARIO" ("usr_id_usuario")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE "IMAGEN" (
  "img_id_imagen" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "img_usr_id_usuario" integer NOT NULL,
  "img_nombre_original" varchar(255) NOT NULL,
  "img_nombre_archivo" varchar(255) NOT NULL,
  "img_formato" varchar(50) NOT NULL,
  "img_ancho_original" integer NOT NULL CHECK ("img_ancho_original" >= 0),
  "img_alto_original" integer NOT NULL CHECK ("img_alto_original" >= 0),
  "img_tamano_bytes" bigint NOT NULL CHECK ("img_tamano_bytes" >= 0),
  "img_hash_archivo" varchar(255) DEFAULT NULL,
  "img_fecha_subida" timestamp DEFAULT CURRENT_TIMESTAMP,
  "img_fecha_modificacion" timestamp DEFAULT NULL,
  "img_estado_imagen" varchar(20) DEFAULT 'activa'
    CHECK ("img_estado_imagen" IN ('activa', 'archivada', 'eliminada')),
  CONSTRAINT "imagen_usuario_fk"
    FOREIGN KEY ("img_usr_id_usuario")
    REFERENCES "USUARIO" ("usr_id_usuario")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX "idx_imagen_usuario" ON "IMAGEN" ("img_usr_id_usuario");
CREATE INDEX "idx_imagen_estado_formato" ON "IMAGEN" ("img_estado_imagen", "img_formato");

CREATE TABLE "SESION_EDICION" (
  "ses_id_sesion" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ses_usr_id_usuario" integer NOT NULL,
  "ses_img_id_imagen" integer DEFAULT NULL,
  "ses_fecha_inicio" timestamp DEFAULT CURRENT_TIMESTAMP,
  "ses_fecha_fin" timestamp DEFAULT NULL,
  "ses_duracion_minutos" integer DEFAULT NULL,
  "ses_estado_sesion" varchar(20) DEFAULT 'activa'
    CHECK ("ses_estado_sesion" IN ('activa', 'pausada', 'finalizada', 'cancelada')),
  "ses_cambios_guardados" boolean DEFAULT false,
  "ses_numero_operaciones" integer DEFAULT 0 CHECK ("ses_numero_operaciones" >= 0),
  CONSTRAINT "sesion_usuario_fk"
    FOREIGN KEY ("ses_usr_id_usuario")
    REFERENCES "USUARIO" ("usr_id_usuario")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "sesion_imagen_fk"
    FOREIGN KEY ("ses_img_id_imagen")
    REFERENCES "IMAGEN" ("img_id_imagen")
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX "idx_sesion_usuario" ON "SESION_EDICION" ("ses_usr_id_usuario");
CREATE INDEX "idx_sesion_imagen" ON "SESION_EDICION" ("ses_img_id_imagen");
CREATE INDEX "idx_sesion_estado_guardados" ON "SESION_EDICION" ("ses_estado_sesion", "ses_cambios_guardados");

CREATE TABLE "OPERACION" (
  "opr_id_operacion" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "opr_ses_id_sesion" integer NOT NULL,
  "opr_usr_id_usuario" integer NOT NULL,
  "opr_tipo_operacion" varchar(100) NOT NULL,
  "opr_parametros" jsonb DEFAULT NULL,
  "opr_fecha_hora" timestamp DEFAULT CURRENT_TIMESTAMP,
  "opr_orden_secuencial" integer NOT NULL CHECK ("opr_orden_secuencial" > 0),
  "opr_estado_operacion" varchar(20) DEFAULT 'completada'
    CHECK ("opr_estado_operacion" IN ('completada', 'revertida', 'error')),
  "opr_tiempo_ejecucion_ms" integer DEFAULT NULL
    CHECK ("opr_tiempo_ejecucion_ms" IS NULL OR "opr_tiempo_ejecucion_ms" >= 0),
  CONSTRAINT "operacion_sesion_fk"
    FOREIGN KEY ("opr_ses_id_sesion")
    REFERENCES "SESION_EDICION" ("ses_id_sesion")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "operacion_usuario_fk"
    FOREIGN KEY ("opr_usr_id_usuario")
    REFERENCES "USUARIO" ("usr_id_usuario")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX "idx_operacion_sesion" ON "OPERACION" ("opr_ses_id_sesion");
CREATE INDEX "idx_operacion_usuario" ON "OPERACION" ("opr_usr_id_usuario");
CREATE INDEX "idx_operacion_estado_tipo" ON "OPERACION" ("opr_estado_operacion", "opr_tipo_operacion");
CREATE INDEX "idx_operacion_estado_fecha" ON "OPERACION" ("opr_estado_operacion", "opr_fecha_hora");

CREATE OR REPLACE VIEW "v_usuarios_activos" AS
SELECT
  u."usr_id_usuario",
  CONCAT(u."usr_nombres", ' ', u."usr_apellidos") AS "nombre_completo",
  u."usr_correo",
  u."usr_fecha_registro",
  u."usr_ultimo_acceso",
  u."usr_sesion_activa",
  COUNT(DISTINCT i."img_id_imagen") AS "total_imagenes",
  COUNT(DISTINCT s."ses_id_sesion") AS "total_sesiones"
FROM "USUARIO" u
LEFT JOIN "IMAGEN" i
  ON u."usr_id_usuario" = i."img_usr_id_usuario"
LEFT JOIN "SESION_EDICION" s
  ON u."usr_id_usuario" = s."ses_usr_id_usuario"
WHERE u."usr_estado_usuario" = 'activo'
GROUP BY
  u."usr_id_usuario",
  u."usr_nombres",
  u."usr_apellidos",
  u."usr_correo",
  u."usr_fecha_registro",
  u."usr_ultimo_acceso",
  u."usr_sesion_activa";
